spring:
    liquibase:
        enabled: true
    datasource:
        url: jdbc:h2:mem:pms
        username: sa
        password: password
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-console
            settings.trace: false
            settings.web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    devtools:
        restart:
            enabled: true
    mvc:
        throw-exception-if-no-handler-found: true
    web:
        resources:
            add-mappings: false
server:
    error:
        whitelabel:
            enabled: false